highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://github.com/PeiChunChang.github.io/
author: Pei-Chun Chang (張珮君)

# edit this section with your information
# myjekyll.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: "/"
title: Pei-Chun Chang's website
name: Pei-Chun Chang <br>張珮君
email: pei.pcchang@gmail.com
email_full: pei.pcchang@gmail.com
website: Link to CV
website_full: ./PCChang_CV.pdf
github: PeiChunChang/

# needed for travis-ci build
exclude: [vendor]

